query GetMenus($restaurantId: String!) {
  getMenus(restaurantId: $restaurantId) {
    categories {
      id
    }
    id
    isActive
    items {
      id
    }
    name
    restaurantId
  }
}
