query GetMenuCategories($menuId: String!) {
  getMenuCategories(menuId: $menuId) {
    id
    name
    order
    items {
      id
      categoryId
      menuId
      dishId
      priceOverride
      dish {
        id
        name
        description
        price
      }
    }
  }
}
