query GetMenu($menuId: String!) {
  getMenu(id: $menuId) {
    categories {
      id
      name
    }
    id
    items {
      categoryId
      id
      menuId
      name
    }
    name
    restaurantId
  }
}
