query GetActiveMenu($restaurantId: String!) {
  getActiveMenu(restaurantId: $restaurantId) {
    id
    name
    isActive
    restaurantId
    categories {
      id
      name
      items {
        id
        priceOverride
        dish {
          id
          name
          description
          price
          ingredients {
            ingredient {
              name
            }
          }
        }
      }
    }
  }
}
