query Menus($restaurantId: String!) {
  menus(restaurantId: $restaurantId) {
    code
    message
    success
    menus {
      categories {
        id
        name
      }
      id
      items {
        id
        menuId
        name
      }
      name
      restaurantId
    }
  }
}
