query Me {
  me {
    id
    name
    email
    image
    hasActiveSubscription
    isDemo
    onboarding {
      hasRestaurant
      restaurantId
      restaurantName
      hasMenu
      hasCategory
      hasDish
      hasTable
      isReady
    }
  }
}
