query GetDashboardRestaurantStatus {
  getDashboardRestaurantStatus {
    name
    menus {
      items {
        category {
          id
        }
        id
      }
      id
    }
    id
    tables {
      id
    }
  }
}
