query GetDashboardSetupStatus {
  dashboardSetupStatus {
    hasRestaurant
    restaurantId
    restaurantName
    hasMenu
    hasMenuCategory
    hasMenuItem
    hasTable
    isFullySetup
  }
}
