query RestaurantDashboardStatus {
  restaurantDashboardStatus {
    id
    name
    tables {
      id
    }
    menus {
      id
      categories {
        id
      }
      items {
        id
      }
    }
  }
}
