query GetRestaurantIngredients($restaurantId: String!) {
  getRestaurantIngredients(restaurantId: $restaurantId) {
    available
    id
    ingredientCategory {
      id
      name
    }
    name
  }
}
