query GetRestaurantIngredients($restaurantId: String!) {
  getRestaurantIngredients(restaurantId: $restaurantId) {
    id
    name
    available
    ingredientCategory {
      id
      name
    }
  }
}
