query GetMenuItem($id: String!) {
  getMenuItem(id: $id) {
    id
    categoryId
    dishId
    priceOverride
    dish {
      id
      name
      description
      price
      ingredients {
        ingredient {
          id
          name
          available
          ingredientCategory {
            id
            name
          }
        }
      }
    }
  }
}
